// Vendors the PDF stylesheets into a TypeScript module so they are bundled
// with the app (works in dev, in `next build`, and on serverless) without
// relying on reading node_modules at runtime.
//
// Run with: npm run gen:css
import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

const markdownCss = await readFile(
  require.resolve("github-markdown-css/github-markdown-light.css"),
  "utf8",
);
const highlightCss = await readFile(
  require.resolve("highlight.js/styles/github.css"),
  "utf8",
);

const esc = (s) => "`" + s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";

const out = `// AUTO-GENERATED by scripts/gen-css.mjs — do not edit by hand.
// Regenerate with: npm run gen:css
/* eslint-disable */
export const MARKDOWN_CSS = ${esc(markdownCss)};

export const HIGHLIGHT_CSS = ${esc(highlightCss)};
`;

await writeFile(new URL("../src/lib/pdf-styles.ts", import.meta.url), out);
console.log("Wrote src/lib/pdf-styles.ts");
